# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import business_pb2 as business__pb2


class BusinessServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/begonia.org.sdk.BusinessService/Add',
                request_serializer=business__pb2.PostBusinessRequest.SerializeToString,
                response_deserializer=business__pb2.Business.FromString,
                )
        self.Update = channel.unary_unary(
                '/begonia.org.sdk.BusinessService/Update',
                request_serializer=business__pb2.PatchBusinessRequest.SerializeToString,
                response_deserializer=business__pb2.Business.FromString,
                )
        self.Get = channel.unary_unary(
                '/begonia.org.sdk.BusinessService/Get',
                request_serializer=business__pb2.GetBusinessRequest.SerializeToString,
                response_deserializer=business__pb2.Business.FromString,
                )
        self.Delete = channel.unary_unary(
                '/begonia.org.sdk.BusinessService/Delete',
                request_serializer=business__pb2.DeleteBusinessRequest.SerializeToString,
                response_deserializer=business__pb2.DeleteBusinessResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/begonia.org.sdk.BusinessService/List',
                request_serializer=business__pb2.ListBusinessRequest.SerializeToString,
                response_deserializer=business__pb2.ListBusinessResponse.FromString,
                )


class BusinessServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BusinessServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=business__pb2.PostBusinessRequest.FromString,
                    response_serializer=business__pb2.Business.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=business__pb2.PatchBusinessRequest.FromString,
                    response_serializer=business__pb2.Business.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=business__pb2.GetBusinessRequest.FromString,
                    response_serializer=business__pb2.Business.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=business__pb2.DeleteBusinessRequest.FromString,
                    response_serializer=business__pb2.DeleteBusinessResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=business__pb2.ListBusinessRequest.FromString,
                    response_serializer=business__pb2.ListBusinessResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'begonia.org.sdk.BusinessService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class BusinessService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.BusinessService/Add',
            business__pb2.PostBusinessRequest.SerializeToString,
            business__pb2.Business.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.BusinessService/Update',
            business__pb2.PatchBusinessRequest.SerializeToString,
            business__pb2.Business.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.BusinessService/Get',
            business__pb2.GetBusinessRequest.SerializeToString,
            business__pb2.Business.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.BusinessService/Delete',
            business__pb2.DeleteBusinessRequest.SerializeToString,
            business__pb2.DeleteBusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.BusinessService/List',
            business__pb2.ListBusinessRequest.SerializeToString,
            business__pb2.ListBusinessResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
