# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import app_pb2 as app__pb2


class AppsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Post = channel.unary_unary(
                '/begonia.org.sdk.AppsService/Post',
                request_serializer=app__pb2.AppsRequest.SerializeToString,
                response_deserializer=app__pb2.AddAppResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/begonia.org.sdk.AppsService/Update',
                request_serializer=app__pb2.AppsRequest.SerializeToString,
                response_deserializer=app__pb2.Apps.FromString,
                )
        self.Get = channel.unary_unary(
                '/begonia.org.sdk.AppsService/Get',
                request_serializer=app__pb2.GetAPPRequest.SerializeToString,
                response_deserializer=app__pb2.Apps.FromString,
                )
        self.Delete = channel.unary_unary(
                '/begonia.org.sdk.AppsService/Delete',
                request_serializer=app__pb2.DeleteAppRequest.SerializeToString,
                response_deserializer=app__pb2.DeleteAppResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/begonia.org.sdk.AppsService/List',
                request_serializer=app__pb2.AppsListRequest.SerializeToString,
                response_deserializer=app__pb2.AppsListResponse.FromString,
                )


class AppsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Post(self, request, context):
        """@gotags: doc:"添加app服务"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """@gotags: doc:"获取app服务"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Post': grpc.unary_unary_rpc_method_handler(
                    servicer.Post,
                    request_deserializer=app__pb2.AppsRequest.FromString,
                    response_serializer=app__pb2.AddAppResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=app__pb2.AppsRequest.FromString,
                    response_serializer=app__pb2.Apps.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=app__pb2.GetAPPRequest.FromString,
                    response_serializer=app__pb2.Apps.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=app__pb2.DeleteAppRequest.FromString,
                    response_serializer=app__pb2.DeleteAppResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=app__pb2.AppsListRequest.FromString,
                    response_serializer=app__pb2.AppsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'begonia.org.sdk.AppsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AppsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.AppsService/Post',
            app__pb2.AppsRequest.SerializeToString,
            app__pb2.AddAppResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.AppsService/Update',
            app__pb2.AppsRequest.SerializeToString,
            app__pb2.Apps.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.AppsService/Get',
            app__pb2.GetAPPRequest.SerializeToString,
            app__pb2.Apps.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.AppsService/Delete',
            app__pb2.DeleteAppRequest.SerializeToString,
            app__pb2.DeleteAppResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.AppsService/List',
            app__pb2.AppsListRequest.SerializeToString,
            app__pb2.AppsListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
