# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import app_pb2 as app__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class AppsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Post = channel.unary_unary(
                '/begonia.org.sdk.AppsService/Post',
                request_serializer=app__pb2.AppsRequest.SerializeToString,
                response_deserializer=app__pb2.AddAppResponse.FromString,
                _registered_method=True)
        self.Update = channel.unary_unary(
                '/begonia.org.sdk.AppsService/Update',
                request_serializer=app__pb2.AppsRequest.SerializeToString,
                response_deserializer=app__pb2.Apps.FromString,
                _registered_method=True)
        self.Get = channel.unary_unary(
                '/begonia.org.sdk.AppsService/Get',
                request_serializer=app__pb2.GetAPPRequest.SerializeToString,
                response_deserializer=app__pb2.Apps.FromString,
                _registered_method=True)
        self.Delete = channel.unary_unary(
                '/begonia.org.sdk.AppsService/Delete',
                request_serializer=app__pb2.DeleteAppRequest.SerializeToString,
                response_deserializer=app__pb2.DeleteAppResponse.FromString,
                _registered_method=True)
        self.List = channel.unary_unary(
                '/begonia.org.sdk.AppsService/List',
                request_serializer=app__pb2.AppsListRequest.SerializeToString,
                response_deserializer=app__pb2.AppsListResponse.FromString,
                _registered_method=True)


class AppsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Post(self, request, context):
        """@gotags: doc:"添加app服务"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """@gotags: doc:"获取app服务"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Post': grpc.unary_unary_rpc_method_handler(
                    servicer.Post,
                    request_deserializer=app__pb2.AppsRequest.FromString,
                    response_serializer=app__pb2.AddAppResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=app__pb2.AppsRequest.FromString,
                    response_serializer=app__pb2.Apps.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=app__pb2.GetAPPRequest.FromString,
                    response_serializer=app__pb2.Apps.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=app__pb2.DeleteAppRequest.FromString,
                    response_serializer=app__pb2.DeleteAppResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=app__pb2.AppsListRequest.FromString,
                    response_serializer=app__pb2.AppsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'begonia.org.sdk.AppsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('begonia.org.sdk.AppsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AppsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.sdk.AppsService/Post',
            app__pb2.AppsRequest.SerializeToString,
            app__pb2.AddAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.sdk.AppsService/Update',
            app__pb2.AppsRequest.SerializeToString,
            app__pb2.Apps.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.sdk.AppsService/Get',
            app__pb2.GetAPPRequest.SerializeToString,
            app__pb2.Apps.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.sdk.AppsService/Delete',
            app__pb2.DeleteAppRequest.SerializeToString,
            app__pb2.DeleteAppResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.sdk.AppsService/List',
            app__pb2.AppsListRequest.SerializeToString,
            app__pb2.AppsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
