# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import endpoint_pb2 as endpoint__pb2


class EndpointServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Post = channel.unary_unary(
                '/begonia.org.sdk.EndpointService/Post',
                request_serializer=endpoint__pb2.EndpointSrvConfig.SerializeToString,
                response_deserializer=endpoint__pb2.AddEndpointResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/begonia.org.sdk.EndpointService/Update',
                request_serializer=endpoint__pb2.EndpointSrvUpdateRequest.SerializeToString,
                response_deserializer=endpoint__pb2.UpdateEndpointResponse.FromString,
                )
        self.Delete = channel.unary_unary(
                '/begonia.org.sdk.EndpointService/Delete',
                request_serializer=endpoint__pb2.DeleteEndpointRequest.SerializeToString,
                response_deserializer=endpoint__pb2.DeleteEndpointResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/begonia.org.sdk.EndpointService/List',
                request_serializer=endpoint__pb2.ListEndpointRequest.SerializeToString,
                response_deserializer=endpoint__pb2.ListEndpointResponse.FromString,
                )
        self.Get = channel.unary_unary(
                '/begonia.org.sdk.EndpointService/Get',
                request_serializer=endpoint__pb2.DetailsEndpointRequest.SerializeToString,
                response_deserializer=endpoint__pb2.DetailsEndpointResponse.FromString,
                )


class EndpointServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Post(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EndpointServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Post': grpc.unary_unary_rpc_method_handler(
                    servicer.Post,
                    request_deserializer=endpoint__pb2.EndpointSrvConfig.FromString,
                    response_serializer=endpoint__pb2.AddEndpointResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=endpoint__pb2.EndpointSrvUpdateRequest.FromString,
                    response_serializer=endpoint__pb2.UpdateEndpointResponse.SerializeToString,
            ),
            'Delete': grpc.unary_unary_rpc_method_handler(
                    servicer.Delete,
                    request_deserializer=endpoint__pb2.DeleteEndpointRequest.FromString,
                    response_serializer=endpoint__pb2.DeleteEndpointResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=endpoint__pb2.ListEndpointRequest.FromString,
                    response_serializer=endpoint__pb2.ListEndpointResponse.SerializeToString,
            ),
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=endpoint__pb2.DetailsEndpointRequest.FromString,
                    response_serializer=endpoint__pb2.DetailsEndpointResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'begonia.org.sdk.EndpointService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EndpointService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Post(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.EndpointService/Post',
            endpoint__pb2.EndpointSrvConfig.SerializeToString,
            endpoint__pb2.AddEndpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.EndpointService/Update',
            endpoint__pb2.EndpointSrvUpdateRequest.SerializeToString,
            endpoint__pb2.UpdateEndpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.EndpointService/Delete',
            endpoint__pb2.DeleteEndpointRequest.SerializeToString,
            endpoint__pb2.DeleteEndpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.EndpointService/List',
            endpoint__pb2.ListEndpointRequest.SerializeToString,
            endpoint__pb2.ListEndpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/begonia.org.sdk.EndpointService/Get',
            endpoint__pb2.DetailsEndpointRequest.SerializeToString,
            endpoint__pb2.DetailsEndpointResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
