# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: begonia/api/v1/options.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x62\x65gonia/api/v1/options.proto\x12\x0e\x62\x65gonia.api.v1\x1a google/protobuf/descriptor.proto:;\n\rauth_reqiured\x12\x1f.google.protobuf.ServiceOptions\x18\xf1\x86\x03 \x01(\x08\x88\x01\x01:B\n\x14method_auth_reqiured\x12\x1f.google.protobuf.ServiceOptions\x18\xf2\x86\x03 \x01(\x08\x88\x01\x01:8\n\x0cun_updatable\x12\x1d.google.protobuf.FieldOptions\x18\xf7\x86\x03 \x01(\x08\x88\x01\x01:4\n\x08validate\x12\x1d.google.protobuf.FieldOptions\x18\xf8\x86\x03 \x01(\t\x88\x01\x01:3\n\x03msg\x12!.google.protobuf.EnumValueOptions\x18\xf4\x86\x03 \x01(\t\x88\x01\x01:2\n\ngo_mod_pkg\x12\x1c.google.protobuf.FileOptions\x18\xf5\x86\x03 \x01(\t:;\n\rhttp_response\x12\x1f.google.protobuf.ServiceOptions\x18\xf6\x86\x03 \x01(\t\x88\x01\x01:C\n\x16\x64ont_use_http_response\x12\x1e.google.protobuf.MethodOptions\x18\xf9\x86\x03 \x01(\x08\x88\x01\x01\x42.Z,github.com/begonia-org/go-sdk/begonia/api/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'begonia.api.v1.options_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/begonia-org/go-sdk/begonia/api/v1'
# @@protoc_insertion_point(module_scope)
