# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugins.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rplugins.proto\x12\x0f\x62\x65gonia.org.sdk\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\"P\n\rPluginRequest\x12%\n\x07request\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x18\n\x10\x66ull_method_name\x18\x02 \x01(\t\"\xad\x01\n\x0ePluginResponse\x12)\n\x0bnew_request\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12?\n\x08metadata\x18\x02 \x03(\x0b\x32-.begonia.org.sdk.PluginResponse.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"P\n\nPluginInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x04 \x01(\t2\xc6\x01\n\rPluginService\x12_\n\x05\x41pply\x12\x1e.begonia.org.sdk.PluginRequest\x1a\x1f.begonia.org.sdk.PluginResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\"\n/v1/plugin:\x01*\x12T\n\x04Info\x12\x16.google.protobuf.Empty\x1a\x1b.begonia.org.sdk.PluginInfo\"\x17\x82\xd3\xe4\x93\x02\x11\x12\x0f/v1/plugin/infoB.Z,github.com/begonia-org/go-sdk/api/plugins/v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'plugins_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/begonia-org/go-sdk/api/plugins/v1'
  _globals['_PLUGINRESPONSE_METADATAENTRY']._options = None
  _globals['_PLUGINRESPONSE_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PLUGINSERVICE'].methods_by_name['Apply']._options = None
  _globals['_PLUGINSERVICE'].methods_by_name['Apply']._serialized_options = b'\202\323\344\223\002\017\"\n/v1/plugin:\001*'
  _globals['_PLUGINSERVICE'].methods_by_name['Info']._options = None
  _globals['_PLUGINSERVICE'].methods_by_name['Info']._serialized_options = b'\202\323\344\223\002\021\022\017/v1/plugin/info'
  _globals['_PLUGINREQUEST']._serialized_start=120
  _globals['_PLUGINREQUEST']._serialized_end=200
  _globals['_PLUGINRESPONSE']._serialized_start=203
  _globals['_PLUGINRESPONSE']._serialized_end=376
  _globals['_PLUGINRESPONSE_METADATAENTRY']._serialized_start=329
  _globals['_PLUGINRESPONSE_METADATAENTRY']._serialized_end=376
  _globals['_PLUGININFO']._serialized_start=378
  _globals['_PLUGININFO']._serialized_end=458
  _globals['_PLUGINSERVICE']._serialized_start=461
  _globals['_PLUGINSERVICE']._serialized_end=659
# @@protoc_insertion_point(module_scope)
