# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import abac_pb2 as abac__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in abac_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ABACServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Auth = channel.unary_unary(
                '/begonia.org.go.access.control.api.v1.ABACService/Auth',
                request_serializer=abac__pb2.AccessContext.SerializeToString,
                response_deserializer=abac__pb2.AccessResponse.FromString,
                _registered_method=True)
        self.PolicyPut = channel.unary_unary(
                '/begonia.org.go.access.control.api.v1.ABACService/PolicyPut',
                request_serializer=abac__pb2.PutPolicyRequest.SerializeToString,
                response_deserializer=abac__pb2.PutPolicyResponse.FromString,
                _registered_method=True)
        self.PolicyPatch = channel.unary_unary(
                '/begonia.org.go.access.control.api.v1.ABACService/PolicyPatch',
                request_serializer=abac__pb2.PutPolicyRequest.SerializeToString,
                response_deserializer=abac__pb2.PatchPolicyResponse.FromString,
                _registered_method=True)
        self.PolicyDelete = channel.unary_unary(
                '/begonia.org.go.access.control.api.v1.ABACService/PolicyDelete',
                request_serializer=abac__pb2.PolicyRequest.SerializeToString,
                response_deserializer=abac__pb2.Policy.FromString,
                _registered_method=True)
        self.PolicyGet = channel.unary_unary(
                '/begonia.org.go.access.control.api.v1.ABACService/PolicyGet',
                request_serializer=abac__pb2.PolicyRequest.SerializeToString,
                response_deserializer=abac__pb2.Policy.FromString,
                _registered_method=True)
        self.PolicyList = channel.unary_unary(
                '/begonia.org.go.access.control.api.v1.ABACService/PolicyList',
                request_serializer=abac__pb2.Policy.SerializeToString,
                response_deserializer=abac__pb2.Policy.FromString,
                _registered_method=True)


class ABACServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Auth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolicyPut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolicyPatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolicyDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolicyGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PolicyList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ABACServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Auth': grpc.unary_unary_rpc_method_handler(
                    servicer.Auth,
                    request_deserializer=abac__pb2.AccessContext.FromString,
                    response_serializer=abac__pb2.AccessResponse.SerializeToString,
            ),
            'PolicyPut': grpc.unary_unary_rpc_method_handler(
                    servicer.PolicyPut,
                    request_deserializer=abac__pb2.PutPolicyRequest.FromString,
                    response_serializer=abac__pb2.PutPolicyResponse.SerializeToString,
            ),
            'PolicyPatch': grpc.unary_unary_rpc_method_handler(
                    servicer.PolicyPatch,
                    request_deserializer=abac__pb2.PutPolicyRequest.FromString,
                    response_serializer=abac__pb2.PatchPolicyResponse.SerializeToString,
            ),
            'PolicyDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.PolicyDelete,
                    request_deserializer=abac__pb2.PolicyRequest.FromString,
                    response_serializer=abac__pb2.Policy.SerializeToString,
            ),
            'PolicyGet': grpc.unary_unary_rpc_method_handler(
                    servicer.PolicyGet,
                    request_deserializer=abac__pb2.PolicyRequest.FromString,
                    response_serializer=abac__pb2.Policy.SerializeToString,
            ),
            'PolicyList': grpc.unary_unary_rpc_method_handler(
                    servicer.PolicyList,
                    request_deserializer=abac__pb2.Policy.FromString,
                    response_serializer=abac__pb2.Policy.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'begonia.org.go.access.control.api.v1.ABACService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('begonia.org.go.access.control.api.v1.ABACService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ABACService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Auth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.go.access.control.api.v1.ABACService/Auth',
            abac__pb2.AccessContext.SerializeToString,
            abac__pb2.AccessResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolicyPut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.go.access.control.api.v1.ABACService/PolicyPut',
            abac__pb2.PutPolicyRequest.SerializeToString,
            abac__pb2.PutPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolicyPatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.go.access.control.api.v1.ABACService/PolicyPatch',
            abac__pb2.PutPolicyRequest.SerializeToString,
            abac__pb2.PatchPolicyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolicyDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.go.access.control.api.v1.ABACService/PolicyDelete',
            abac__pb2.PolicyRequest.SerializeToString,
            abac__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolicyGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.go.access.control.api.v1.ABACService/PolicyGet',
            abac__pb2.PolicyRequest.SerializeToString,
            abac__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PolicyList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/begonia.org.go.access.control.api.v1.ABACService/PolicyList',
            abac__pb2.Policy.SerializeToString,
            abac__pb2.Policy.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
